theme: jekyll-theme-minimal
title: Álvaro Otaegui
logo: /assets/images/profile.png
description:  Data Analysis and Project Manager at Latin-American Laboratory for Assessment of the Quality of Education (LLECE)