project:
  type: website
  output-dir: _site

website:
  title: "Álvaro Otaegui"
  description: "Personal website"
  search: false
  navbar:
      left:
      - href: index.qmd

format:
  html:
    template: _templates/minimal.html
    theme: cosmo
    css: assets/css/style.css
    toc: false

    include-after-body:
      - text: |
          <script>
          document.addEventListener('DOMContentLoaded', function() {
            const header = document.querySelector('header');
            const title = header.querySelector('h1');
            const profile = document.querySelector('.sidebar-profile');
            
            if (title && profile) {
              // Crear un espaciador
              const spacer = document.createElement('div');
              spacer.style.height = '15px';  // Ajusta este valor según necesites
              
              // Insertar primero el espaciador y luego la imagen
              title.insertAdjacentElement('afterend', spacer);
              spacer.insertAdjacentElement('afterend', profile);
            }
          });
          </script>


