project:
  type: website
  output-dir: docs

website:
  title: "Álvaro Otaegui"
  search: false
  navbar:
    #search: false
    #left
    right:
      - href: index.qmd
        text: About
      - cv.qmd
      - research.qmd
      - teaching.qmd
      - blog.qmd
    sidebar:
      search: false

resources:
  - CNAME

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



