---
title: "El sentido de evaluar a toda costa: un diagnostico de desconfianza"
author: "Álvaro Otaegui"
date: "05/06/2020"
categories:
    - Columna
---

La intención del Gobierno por querer aplicar el Simce como evaluación diagnóstica ha sido ampliamente criticada. No sin justa razón, los opositores a esta medida han planteado que en el contexto actual su aplicación no entregaría información valiosa y sólo estaría hipotecando su credibilidad[^1]. Pero ¿es sólo el SIMCE el que refleja problemas de credibilidad, o hay detrás un problema mayor que le compete también al resto de las evaluaciones nacionales de gran escala?

Las evaluaciones nacionales de gran escala no son ninguna novedad en nuestro país. Estas comienzan de forma gradual en el siglo XIX con el sistema de inspectores y el bachillerato[^2]. Luego continúan y se consolidan durante el siglo XX con la Prueba de Aptitud Académica (PAA) y el Simce, agregándose en la actualidad la Prueba de Selección Universitaria (PSU) y la Evaluación Docente. Aunque todas estas evaluaciones surgieron con distintos propósitos, actualmente se espera que todas entreguen información que retroalimente el desempeño educacional de las escuelas y oriente la dirección de la política pública. Así, mientras el Bachillerato y la PAA buscaban en principio ser instrumentos de selección e ingreso a la educación superior, las evaluaciones escolares como el Simce y la Evaluación Docente surgieron con el objetivo de monitorear (controlar) la calidad de la enseñanza, siendo su principal promesa entregar constantemente información al sistema escolar para realizar mejoras. A inicios del siglo XXI con el cambio de la PAA a la PSU, aunque conservando su objetivo de selección, esta se sumó al propósito de monitoreo y mejoramiento, particularmente del curriculum de enseñanza media. De esta manera, y dejando de lado toda la complejidad de los incentivos y efectos que estos generan en la cotidianidad de las escuelas, se ha esperado que las evaluaciones escolares entreguen información precisa y confiable sobre dimensiones previamente definidas para que el sistema se permita constantemente mejorar.

En vista de la larga y controvertida historia de estos instrumentos, resulta sensato entonces poder echarle mano al basto conocimiento y experiencia acumulada en esta materia para no cometer grandes errores. Pese a todo, nunca nos habíamos enfrentado a un contexto tan adverso y lleno de incertidumbre como el actual. Ante esto, ¿será entonces oportuna la aplicación de evaluaciones masivas diseñadas para monitorear e informar sobre la calidad del sistema en un contexto tan distinto al que vivimos actualmente?

Aunque noble y deseable, me atrevería a decir que aquello que se dice perseguir a través de las evaluaciones masivas esconde más bien una gran desconfianza hacia el trabajo de los docentes y escuelas. Es a causa de esta desconfianza que no debería extrañarnos los incansables intentos por continuar aplicando estos instrumentos, aun ante una situación de crisis como la que estamos viviendo. Por consiguiente, el mandato continuará siendo que el Simce sea aplicado de forma “diagnóstica” incluso ante estallidos sociales y pandemias mundiales; que la PSU (o cualquier evaluación que la reemplace) siga su curso pese al poco tiempo que tendrán los estudiantes y escuelas para prepararse ante el ajuste curricular anunciado para este año y que la Evaluación Docente siga midiendo las competencias de los y las profesoras, aunque no puedan rendir las etapas del portafolio de forma regular (con tiempo para alistarse, conocer las necesidades de los estudiantes, menores niveles de estrés y menos incertidumbre del que ya existe sobre el proceso).

¿Son entonces las evaluaciones escolares innecesarias? Claro que no, estas son extremadamente valiosas cuando, al ser un medio, entregan información que les permite al sistema en su conjunto mejorar. No obstante, pierden gran parte de su sentido y valor social cuando al ser un fin en sí mismas, olvidan y ocultan sus principales motivos, dejando de levantar información que sirva para orientar los desafíos actuales de las comunidades educativas. Más aun si la historia nos ha demostrado que además la información levantada hasta la fecha por los distintos instrumentos tampoco ha significado un mejoramiento sustantivo en la calidad del sistema. Asimismo, el hecho de levantar información a toda costa sólo para los fines de informar a la política publica posiciona al gobierno en una desconexión total con la realidad, reflejando al mismo tiempo esta desconexión una falta de empatía profunda con nuestras comunidades.

Ante esto, me parece que la hipótesis que maneja el Gobierno en cuanto a que la aplicación de evaluaciones masivas en el contexto actual entrega información valiosa, aún cuando no es la información que nuestras comunidades educativas necesitan el día de hoy para afrontar sus desafíos, no sólo hipoteca la credibilidad del sistema de evaluación en su conjunto, sino que acentúa también el problema de desconfianza que existe por parte de las autoridades hacia nuestras escuelas y docentes. Por esto, antes de levantar cualquier clase información, resulta crucial preguntarse: ¿qué necesitamos hoy? A mi parecer, lo que hoy las comunidades educativas necesitan es tiempo para reflexionar, apoyo técnico para enfrentar los desafíos actuales desde su propia realidad y, ante todo, confianza por parte de nuestros gobernantes.

[^1]: Vease opiniones de Cristián Bellei ([Ciper](https://www.ciperchile.cl/2020/05/16/simce-despues-del-confinamiento-servira-para-algo/)),  Alejandra Falabella (La Tercera) y Carolina Flores (La Segunda).
[^2]: Para más información revisar Ramos y Falabella (2019)